改善案の実装
tomitahisaki/mokumoku pull request #2
Opened 2023-01-26 10:34 UTC by tomitahisaki

### 選択した事業側の課題
直近一年間で、2回以上もくもく会に参加してくれた人は利用者全体の1%のみ。もくもく会で気の合う仲間を見つけられなかったのではないか？

<a href="https://gyazo.com/b7f839514513aa4ba5c067b92493c22b"><img src="https://i.gyazo.com/b7f839514513aa4ba5c067b92493c22b.png" alt="Image from Gyazo" width="653"/></a>

2023-01-26 10:47 UTC, busitora requested changes
コメントしました〜！

2023-01-26 10:47 UTC, busitora commented on app/models/relationship.rb
> +  belongs_to :followed, class_name: "User"
followed はあまり フォロワー フォローでは一般的ではない気がしますが、どこ参考にされましたか？

2023-01-26 10:47 UTC, busitora commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
`relationships.find_by(followed_id: user_id)` が nil の時に destoryすると エラーになります。
ご確認ください

2023-01-26 10:47 UTC, busitora commented on app/views/users/_follow_button.html.erb
> +<% unless current_user == user %>
`current_user == user`
こちらの 処理は、モデルメソッドにうつしてください

2023-01-26 14:38 UTC, tomitahisaki commented on app/models/relationship.rb
> +  belongs_to :followed, class_name: "User"
コメントありがとうございます！
今回はqiita記事を参考にさせていただきました。
https://qiita.com/nakachan1994/items/e6107fe3003f6515e385
今回の機能については、userとfollow(userモデルを参照)とするもので書いたほうが良いのでしょうか？
中間テーブルのカラムがどちらもuserテーブルを参照しているので、理解しづらく、英語直訳でわかるような書き方としました。

2023-01-26 14:38 UTC, tomitahisaki commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
nil時のエラーを回避するために、if文で判定させるようにしました
他に方法がありましたら、ご教示願います！

2023-01-26 14:38 UTC, tomitahisaki commented on app/views/users/_follow_button.html.erb
> +<% unless current_user == user %>
モデルメソッドへ移しました！
書き方等におかしなところがありましたら、ご指摘願います！

2023-01-29 01:44 UTC, tomitahisaki commented
[![Image from Gyazo](https://i.gyazo.com/2a344cd49fd2e0adfa2bb0c0c7c13dc1.png)](https://gyazo.com/2a344cd49fd2e0adfa2bb0c0c7c13dc1)

DS.storeが入っていたので、revertして再度commit しました(不手際有りましたら、教えて下さい)
Rspecを実行した結果を、添付してあります.
メソッド名のみ変更しました。　

2023-01-29 07:36 UTC, takyyk commented
@tomitahisaki 
LGTMです！

2023-01-29 14:08 UTC, merged